id: P007882
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG3410
  title: གཅོད་ཚོགས་ཡོན་ཏན་ཀུན་འབྱུང་
  author: ''
  volumes:
    b306b71262fc49caa545cc0bba6b8fdd:
      image_group_id: I1KG3502
      title: ''
      volume_number: 1
      total_pages: 174
ebook_metadata:
  title: གཅོད་ཚོགས་ཡོན་ཏན་ཀུན་འབྱུང་
  author: ''
  sku: P007882
  cover: cover.jpg
  layers:
  - pagination
